export const SHINOBI_ASSIGNED_TASK_TIMEOUT_BASE = 10e3;
export const SHINOBI_IDLE_TASK_TIMEOUT_BASE = 10e3;
export const SHINOBI_INJURED_TIMEOUT_BASE = 15e3;

export const VILLAGE_TASK_GENERATION_TIMEOUT_BASE = 15e3;
